"""Added column fs_uniquifier to table users

Revision ID: 03b2df14b760
Revises: aad056c21b18
Create Date: 2024-02-08 11:05:41.278859

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '03b2df14b760'
down_revision = 'aad056c21b18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('Users', schema=None) as batch_op:
    #     batch_op.drop_index('email')
    #     batch_op.drop_index('fs_uniquifier')

    # op.drop_table('Users')
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('RoleID', sa.Integer(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('user_roles_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('user_roles_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'roles', ['RoleID'], ['id'])
        batch_op.drop_column('role_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fs_uniquifier', sa.String(length=255), nullable=False))
        batch_op.alter_column('email_confirmed_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['fs_uniquifier'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('email_confirmed_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_column('fs_uniquifier')

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_roles_ibfk_2', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('user_roles_ibfk_1', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('RoleID')

    op.create_table('Users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email_confirmed_at', mysql.DATETIME(), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('fs_uniquifier', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.create_index('fs_uniquifier', ['fs_uniquifier'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)

    # ### end Alembic commands ###
