"""I products set unique to false

Revision ID: 19753a365a5f
Revises: 947850c24c31
Create Date: 2024-02-26 15:01:01.689209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19753a365a5f'
down_revision = '947850c24c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.drop_index('Image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.create_index('Image', ['Image'], unique=True)

    # ### end Alembic commands ###
