"""Added tables Newsletters, Subscribers

Revision ID: 4283f3c4821b
Revises: 9898910fd27b
Create Date: 2024-02-09 10:19:17.401992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4283f3c4821b'
down_revision = '9898910fd27b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Newsletters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=False),
    sa.Column('last_edit', sa.DateTime(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('date_sent', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email_confirmed_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email_confirmed_at',
               existing_type=mysql.DATETIME(),
               nullable=False)

    op.drop_table('Subscribers')
    op.drop_table('Newsletters')
    # ### end Alembic commands ###
