"""Alterered Subscriber.email to String(255)

Revision ID: 86ded97a6da6
Revises: 4283f3c4821b
Create Date: 2024-02-13 09:50:03.154427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86ded97a6da6'
down_revision = '4283f3c4821b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Subscribers', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Subscribers', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
