"""Added Category.Image column

Revision ID: 8bd91fc90cdd
Revises: 86ded97a6da6
Create Date: 2024-02-14 09:55:13.503991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd91fc90cdd'
down_revision = '86ded97a6da6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Image', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['Image'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('Image')

    # ### end Alembic commands ###
