"""added decription , and image in products

Revision ID: c30f11ec73c8
Revises: 8bd91fc90cdd
Create Date: 2024-02-26 14:38:12.543728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c30f11ec73c8'
down_revision = '8bd91fc90cdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('Description', sa.String(length=200), nullable=False))
        batch_op.create_unique_constraint(None, ['Image'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('Description')
        batch_op.drop_column('Image')

    # ### end Alembic commands ###
